name: artivatic_ai
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.2 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.1
  json_annotation: ^4.4.0
  flutter: 
    sdk: flutter
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.2.0

dev_dependencies: 
  get_cli: ^1.7.1
  flutter_lints: ^1.0.0
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  flutter_launcher_icons: ^0.9.2
  flutter_native_splash: ^2.1.2+1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
    - assets/images/


#  flutter pub run flutter_launcher_icons:main

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo.png"


#  flutter pub run flutter_native_splash:create

flutter_native_splash:
  image: assets/images/logo.png
  color: "#ffffff"
  android: true
  android_gravity: center
  ios: true
  ios_content_mode: center
  fullscreen: true
  android_12:

